/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praone;

import java.awt.Color;
import java.util.HashSet;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.event.TableColumnModelEvent;
import javax.swing.table.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Денис
 */
public class NewJFrame extends javax.swing.JFrame {
    
    // first task
    private int firstTaskCounter = 0;
    private int fTlastRow = 0;
    private int fTlastCol = 0;
    //-first task
    //second task
    private final ChessFigure[] chess = new ChessFigure[6];
    private ChessFigure selected = null;
    //-second task
    //third task
    private boolean humanFirst;
    private boolean isEasy;
    private boolean gameStart = false;
    Player first, second;
    //-third task
    //fith task
    private int guessNumber;
    //fith task
    private FPart blank; 
    // last task
    boolean selField = false;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        for (int i = 1; i < 4; i++)
        {
            chess[i-1] = new Queen(2, i, this.MoveFTable2, this.Score2);
            chess[i+2] = new Bishop(0, i, this.MoveFTable2, this.Score2);
        }
        blank = new FPart(3, 3, null, Task6Table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MoveFTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Score2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        FieldTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jRBeasy = new javax.swing.JRadioButton();
        jRBhard = new javax.swing.JRadioButton();
        j3PCstart = new javax.swing.JToggleButton();
        j3HumanStart = new javax.swing.JToggleButton();
        t3Start = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jSqare4 = new javax.swing.JTable();
        startButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        GuessField5 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        startButton5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        mTable5 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TextField5 = new javax.swing.JTextField();
        startPCButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        isPrimitive5 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Task6Table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        JogaTable7 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setName(""); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null, null},
                {"2", null, null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null, null},
                {"9", null, null, null, null, null, null, null, null, null, null},
                {"10", null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(50);
        jTable1.setShowGrid(true);
        jTable1.setRowSelectionAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("0");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("1");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("2");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("3");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("4");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("5");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("6");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("7");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("8");
            jTable1.getColumnModel().getColumn(9).setHeaderValue("9");
            jTable1.getColumnModel().getColumn(10).setHeaderValue("10");
        }
        DefaultTableCellRenderer  r = (DefaultTableCellRenderer)
        jTable1.getDefaultRenderer(String.class);
        //по горизонтали не выравнивается
        r.setHorizontalAlignment(JLabel.CENTER);
        r.setVerticalAlignment(JLabel.TOP);

        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            for (int j = 1; j < jTable1.getColumnCount(); j++)
            jTable1.setValueAt("", i, j);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ход Конем", jPanel1);

        MoveFTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "♗", "♗", "♗"},
                {"1", "", "", ""},
                {"2", "♛", "♛", "♛"}
            },
            new String [] {
                "", "A", "B", "С"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MoveFTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MoveFTable2.setRowHeight(50);
        MoveFTable2.setRowSelectionAllowed(false);
        MoveFTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        MoveFTable2.setShowGrid(true);
        MoveFTable2.getColumnModel().getColumn(0).setMinWidth(20);
        MoveFTable2.getColumnModel().getColumn(0).setMaxWidth(20);
        MoveFTable2.getColumnModel().getColumn(0).setPreferredWidth(20);
        MoveFTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoveFTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MoveFTable2);
        DefaultTableCellRenderer  r1 = (DefaultTableCellRenderer)
        MoveFTable2.getDefaultRenderer(String.class);
        //по горизонтали не выравнивается
        r1.setHorizontalAlignment(JLabel.CENTER);
        r1.setVerticalAlignment(JLabel.TOP);

        Score2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Фигура", "Клетка n-1", "Клетка n"
            }
        ));
        jScrollPane3.setViewportView(Score2);
        Score2.setShowGrid(true);
        DefaultTableCellRenderer  r3 = (DefaultTableCellRenderer)
        Score2.getDefaultRenderer(String.class);
        //по горизонтали не выравнивается
        r3.setHorizontalAlignment(JLabel.CENTER);
        r3.setVerticalAlignment(JLabel.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Переставь фигуры", jPanel2);

        FieldTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", ""},
                {"", "", ""},
                {"", "", ""}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FieldTable3.setRowHeight(100);
        FieldTable3.setRowSelectionAllowed(false);
        FieldTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(FieldTable3);
        if (FieldTable3.getColumnModel().getColumnCount() > 0) {
            FieldTable3.getColumnModel().getColumn(2).setResizable(false);
        }
        FieldTable3.getTableHeader().setVisible(false);
        FieldTable3.setShowGrid(true);

        jLabel1.setText("Алгоритм игры компьютера");

        buttonGroup1.add(jRBeasy);
        jRBeasy.setText("Простой");

        buttonGroup1.add(jRBhard);
        jRBhard.setText("Сложный");

        buttonGroup2.add(j3PCstart);
        j3PCstart.setText("Начинает компьютер");

        buttonGroup2.add(j3HumanStart);
        j3HumanStart.setText("Начинает человек");

        t3Start.setText("Начать игру");
        t3Start.setToolTipText("");
        t3Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBhard)
                            .addComponent(jRBeasy))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(j3PCstart)
                .addGap(56, 56, 56)
                .addComponent(j3HumanStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t3Start)
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jRBeasy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBhard)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j3PCstart)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j3HumanStart)
                        .addComponent(t3Start)))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Крестики нолики", jPanel3);

        jSqare4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSqare4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jSqare4.getTableHeader().setVisible(false);
        jSqare4.setShowGrid(true);
        jSqare4.setRowHeight(100);
        jSqare4.setRowSelectionAllowed(false);
        jScrollPane6.setViewportView(jSqare4);

        startButton4.setText("Начать игру");
        startButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(startButton4)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton4)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Магический квадрат", jPanel4);

        GuessField5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GuessField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuessField5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(GuessField5);

        jLabel2.setText("Игровое поле");

        startButton5.setText("Начать игру");
        startButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButton5ActionPerformed(evt);
            }
        });

        mTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Число", "Результат"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(mTable5);
        mTable5.getColumnModel().getColumn(0).setMinWidth(60);
        mTable5.getColumnModel().getColumn(0).setMaxWidth(60);
        mTable5.getColumnModel().getColumn(0).setPreferredWidth(60);

        jLabel3.setText("Число, задуманное человеком");

        TextField5.setText("12");

        startPCButton5.setText("Угадывает компьютер");
        startPCButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPCButton5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Алгоритм угадывания числа");

        buttonGroup3.add(isPrimitive5);
        isPrimitive5.setText("Примитивный");

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setText("Сложный");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(startButton5))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startPCButton5)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextField5))
                                    .addComponent(jLabel4)
                                    .addComponent(isPrimitive5)
                                    .addComponent(jRadioButton2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton5)
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startPCButton5)
                .addGap(77, 77, 77)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isPrimitive5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Угадайка", jPanel5);

        Task6Table.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Task6Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(12),  new Integer(9),  new Integer(6),  new Integer(14)},
                { new Integer(10),  new Integer(2),  new Integer(15),  new Integer(11)},
                { new Integer(1),  new Integer(4),  new Integer(5),  new Integer(13)},
                { new Integer(8),  new Integer(7),  new Integer(3), null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Task6Table.setRowHeight(100);
        Task6Table.setRowSelectionAllowed(false);
        Task6Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Task6TableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(Task6Table);
        Task6Table.getTableHeader().setVisible(false);
        Task6Table.setShowGrid(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Пятнашки", jPanel6);

        JogaTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"X", "X", "O", "O", "O", "X", "X"},
                {"X", "X", "O", "O", "O", "X", "X"},
                {"O", "O", "O", "O", "O", "O", "O"},
                {"O", "O", "O", null, "O", "O", "O"},
                {"O", "O", "O", "O", "O", "O", "O"},
                {"X", "X", "O", "O", "O", "X", "X"},
                {"X", "X", "O", "O", "O", "X", "X"}
            },
            new String [] {
                "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JogaTable7.setRowHeight(70);
        JogaTable7.setRowSelectionAllowed(false);
        JogaTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JogaTable7MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(JogaTable7);
        JogaTable7.getTableHeader().setVisible(false);
        JogaTable7.setShowGrid(true);

        JogaTable7.setValueAt("", 3, 3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Йога", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        if (isMovePossible(row, column) == false)
        {
           for (int i = 0; i < jTable1.getRowCount(); i++)
           {
               for (int j = 1; j < jTable1.getColumnCount(); j++)
                   jTable1.setValueAt("", i, j);
           }
           JOptionPane.showMessageDialog(rootPane, "Больше ходить некуда. Ваш результат : " + firstTaskCounter + " закрашенных клеток", "Конец игры", 2);
           firstTaskCounter = 0;
        }
        if (column != 0)
        {
            if (firstTaskCounter == 0)
            {
                jTable1.setValueAt("♘", row, column);
                fTlastRow = row;
                fTlastCol = column;
            }
            else 
            {
                if (trueMove(row, column))
                {
                   jTable1.setValueAt("♘", row, column);  
                   fTlastRow = row;
                   fTlastCol = column;
                }
            }
        }
        firstTaskCounter++;
    }//GEN-LAST:event_jTable1MouseClicked

    private void MoveFTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveFTable2MouseClicked
        if (selected == null)
        {
            for (int i = 0; i < 6; i++)
            {
                if (chess[i].datU(MoveFTable2.getSelectedRow(), MoveFTable2.getSelectedColumn()))
                    selected = chess[i];
            }
            return;
        }
        selected.MoveTo(MoveFTable2.getSelectedRow(), MoveFTable2.getSelectedColumn());
        selected = null;
        for (int i = 0; i < 6; i++)
        {
            if (!chess[i].inPlace())
                return;
        }
        JOptionPane.showMessageDialog(rootPane, "Фигуры переставлены, конец игры", "Конец игры", 2);
        
    }//GEN-LAST:event_MoveFTable2MouseClicked

    private void FieldTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldTable3MouseClicked
        if (gameStart)
        {
            first.Move();
            second.Move();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTable3MouseClicked

    private void t3StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3StartActionPerformed
        if (!j3HumanStart.isSelected() && !j3PCstart.isSelected())
            return;
        if (!jRBeasy.isSelected() && !jRBhard.isSelected())
            return;
        for (int i = 0; i < 3; i++)
            for (int j = 0; j < 3; j++)
                this.FieldTable3.setValueAt("", i, j);
        humanFirst = j3HumanStart.isSelected();
        isEasy = this.jRBeasy.isSelected();
        gameStart = true;
        if (humanFirst)
        {
            this.first = new HumanPlayer("X", this.FieldTable3);
            this.second = new PCPlayer("O", this.FieldTable3, isEasy);
        } else
        {
            this.first = new HumanPlayer("O", this.FieldTable3);
            this.second = new PCPlayer("X", this.FieldTable3, isEasy);
            second.Move();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t3StartActionPerformed

    private void startButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButton4ActionPerformed
        int[][] array = new int[3][3];
        int sum = 0;
        for (int i = 0; i < 3; i++)
        {
            for (int j = 0; j < 3; j++)
            {
                if (jSqare4.getModel().getValueAt(i,j) == null)
                {
                    JOptionPane.showMessageDialog(rootPane, "Не должно быть пустых клеток");
                    return;
                }
                array[i][j] = Integer.parseInt(jSqare4.getModel().getValueAt(i, j).toString());
                if (array[i][j] == 0)
                {
                    JOptionPane.showMessageDialog(rootPane, "Не должно быть нулевых клеток");
                    return;
                }
                sum += array[i][j];
            }
        }
        for (int i = 0; i < 3; i++)
        {
            for (int j = 0; j < 3; j++)
            {
                for (int k = i; k < 3; k++)
                    for (int l = j; l < 3; l++)
                    {
                        if (i != k || l != j)
                            if (array[i][j] == array[k][l])
                            {
                                JOptionPane.showMessageDialog(rootPane, "Не должно быть повторов клеток");
                                return;
                            }
                    }
            }
        }
        int a = 0;
        for (int i = 0; i < 3; i++)
        {
            a += array[0][i] - 2 * array[1][i] + array[2][i];
            a += array[i][0] - 2 * array[i][1] + array[i][2];
        }
        a += array[0][0] + array [2][2] - array[0][2] - array[2][0];
        if (a == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Магический квадрат сошелся");
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "не получилось");
        return;
    }//GEN-LAST:event_startButton4ActionPerformed

    private void startButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) mTable5.getModel();
        model.setRowCount(0);
        guessNumber = ThreadLocalRandom.current().nextInt(0, 18);
    }//GEN-LAST:event_startButton5ActionPerformed

    private void GuessField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuessField5MouseClicked
        for (int i = 0; i < GuessField5.getColumnCount(); i++)
        {
            GuessField5.getModel().setValueAt("", 0, i);
        }
        GuessField5.getModel().setValueAt("X", 0, GuessField5.getSelectedColumn());
        if (this.GuessField5.getSelectedColumn() == guessNumber)
        {
            DefaultTableModel model = (DefaultTableModel) this.mTable5.getModel();
            model.addRow(new Object[]{this.GuessField5.getSelectedColumn(), "Правильное число!"});
            JOptionPane.showMessageDialog(rootPane, "Победа!");
            return;
        }        
        if (this.GuessField5.getSelectedColumn() > guessNumber)
        {
            DefaultTableModel model = (DefaultTableModel) this.mTable5.getModel();
            model.addRow(new Object[]{this.GuessField5.getSelectedColumn(), "Ваше число больше!"});
        }
        if (this.GuessField5.getSelectedColumn() < guessNumber)
        {
            DefaultTableModel model = (DefaultTableModel) this.mTable5.getModel();
            model.addRow(new Object[]{this.GuessField5.getSelectedColumn(), "Ваше число меньше!"});
        }
// TODO add your handling code here:
    }//GEN-LAST:event_GuessField5MouseClicked

    private void startPCButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPCButton5ActionPerformed
        int theNumber;
        DefaultTableModel model = (DefaultTableModel) mTable5.getModel();
        model.setRowCount(0);
        try
        {   
            
            theNumber = Integer.parseInt(this.TextField5.getText()); 
            if (theNumber < 0 || theNumber > 100)
                throw new Exception();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Введите натуральное число");
            return;
        }
        if (this.isPrimitive5.isSelected())
        {
            int guess;
            int min = 0;
            int max = 100;
            do
            {
                guess = ThreadLocalRandom.current().nextInt(min, max );
                if (guess > theNumber)
                {
                    model.addRow(new Object[]{guess, "Ваше число больше!"});
                    max = guess;
                }
                if (guess < theNumber)
                {
                    model.addRow(new Object[]{guess, "Ваше число меньше!"});
                    min = guess + 1;
                }
            } while (guess != theNumber);
            model.addRow(new Object[]{guess, "В точку!"});    
            
        } else
        {
            int guess;
            int min = 0, max = 100;
            do
            {
                guess = (min + max) / 2;
                if (guess > theNumber)
                {
                    model.addRow(new Object[]{guess, "Ваше число больше!"});
                    max = guess;
                }
                if (guess < theNumber)
                {
                    model.addRow(new Object[]{guess, "Ваше число меньше!"});
                    min = guess + 1;
                }
            } while (guess != theNumber);
            model.addRow(new Object[]{guess, "В точку!"});
        }
    }//GEN-LAST:event_startPCButton5ActionPerformed

    private void Task6TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Task6TableMouseClicked
        FPart selected = new FPart(Task6Table.getSelectedRow(), Task6Table.getSelectedColumn(), (Integer) Task6Table.getModel().getValueAt(Task6Table.getSelectedRow(), Task6Table.getSelectedColumn()), Task6Table);
        blank = selected.Move(blank);
        if (isGameFinished())
        {
            JOptionPane.showMessageDialog(rootPane, "Игра окончена!");
        }
    }//GEN-LAST:event_Task6TableMouseClicked

    private JogaF element;
    
    private void JogaTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JogaTable7MouseClicked
        if (selField)
        {
            element.Move(this.JogaTable7.getSelectedRow(), this.JogaTable7.getSelectedColumn());
        } else
        {
            element = new JogaF(this.JogaTable7.getSelectedRow(), this.JogaTable7.getSelectedColumn(), this.JogaTable7);
        }
        selField = !selField;
        if (isJogaIt())
        {
            JOptionPane.showMessageDialog(rootPane, "Игра окончена!");
        }
    }//GEN-LAST:event_JogaTable7MouseClicked
    
    private boolean isJogaIt()
    {
        int c = 0;
        for (int i = 0; i < 7; i++)
            for (int j = 0; j < 7; j++)
            {
                if (this.JogaTable7.getValueAt(i,j).toString() == "O")
                    c++;
            }
        if (c == 1)
            return true;
        return false;
    }
    
    private boolean isGameFinished()
    {
        try {if (((Integer) Task6Table.getValueAt(0, 0) == 1) &&
                (Integer) Task6Table.getValueAt(0, 1) == 2 &&
                (Integer) Task6Table.getValueAt(0, 2) == 3 &&
                (Integer) Task6Table.getValueAt(0, 3) == 4 &&
                (Integer) Task6Table.getValueAt(1, 0) == 5 &&
                (Integer) Task6Table.getValueAt(1, 1) == 6 &&
                (Integer) Task6Table.getValueAt(1, 2) == 7 &&
                (Integer) Task6Table.getValueAt(1, 3) == 8 &&
                (Integer) Task6Table.getValueAt(2, 0) == 9 &&
                (Integer) Task6Table.getValueAt(2, 1) == 10 &&
                (Integer) Task6Table.getValueAt(2, 2) == 11 &&
                (Integer) Task6Table.getValueAt(2, 3) == 12 &&
                (Integer) Task6Table.getValueAt(3, 0) == 13 &&
                (Integer) Task6Table.getValueAt(3, 1) == 14 &&
                (Integer) Task6Table.getValueAt(3, 2) == 15)
            return true;
        }
        catch(Exception e)
        {
            return false;
        }
        return false;
                
    }
    
    private boolean trueMove(int row, int column)
    {
        if (jTable1.getValueAt(row, column).toString() != "")
            return false;
        if (row == fTlastRow + 1 && column == fTlastCol + 2)
            return true;
        if (row == fTlastRow + 1 && column == fTlastCol - 2)
            return true;
        if (row == fTlastRow - 1 && column == fTlastCol + 2)
            return true;
        if (row == fTlastRow - 1 && column == fTlastCol - 2)
            return true;
        if (row == fTlastRow + 2 && column == fTlastCol + 1)
            return true;
        if (row == fTlastRow + 2 && column == fTlastCol - 1)
            return true;
        if (row == fTlastRow - 2 && column == fTlastCol + 1)
            return true;
        if (row == fTlastRow - 2 && column == fTlastCol - 1)
            return true;

        return false;
    }
    
    private boolean isMovePossible(int row, int columnt)
    {
        try
        {
            if (jTable1.getValueAt(row + 1, columnt + 2).toString() == "")
                return true;
        }
        catch(Exception e) {}
        try
        {
            if (jTable1.getValueAt(row - 1, columnt + 2).toString() == "")
                return true;
        }
        catch(Exception e) {}
        try
        {
            if (jTable1.getValueAt(row + 1, columnt - 2).toString() == "")
                return true;
        }
        catch(Exception e) {}
        try
        {
            if (jTable1.getValueAt(row - 1, columnt - 2).toString() == "")
                return true;
        }
        catch(Exception e) {}
        try
        {
            if (jTable1.getValueAt(row + 2, columnt + 1).toString() == "")
                return true;
        }
        catch(Exception e) {}
        try
        {
            if (jTable1.getValueAt(row - 2, columnt + 1).toString() == "")
                return true;
        }
        catch(Exception e) {}
        try
        {
            if (jTable1.getValueAt(row + 2, columnt - 1).toString() == "")
                return true;
        }
        catch(Exception e) {}
        try
        {
            if (jTable1.getValueAt(row - 2, columnt - 1).toString() == "")
                return true;
        }
        catch(Exception e) {}
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FieldTable3;
    private javax.swing.JTable GuessField5;
    private javax.swing.JTable JogaTable7;
    private javax.swing.JTable MoveFTable2;
    private javax.swing.JTable Score2;
    private javax.swing.JTable Task6Table;
    private javax.swing.JTextField TextField5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton isPrimitive5;
    private javax.swing.JToggleButton j3HumanStart;
    private javax.swing.JToggleButton j3PCstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRBeasy;
    private javax.swing.JRadioButton jRBhard;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jSqare4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable mTable5;
    private javax.swing.JButton startButton4;
    private javax.swing.JButton startButton5;
    private javax.swing.JButton startPCButton5;
    private javax.swing.JButton t3Start;
    // End of variables declaration//GEN-END:variables
}
